# Generated by Django 5.2.7 on 2026-07-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('designation', models.CharField(db_index=True, max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joining_date', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='departments.department')),
            ],
            options={
                'ordering': ['first_name'],
                'indexes': [models.Index(fields=['first_name'], name='employees_e_first_n_ac154b_idx'), models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'), models.Index(fields=['designation'], name='employees_e_designa_f93e1c_idx'), models.Index(fields=['salary'], name='employees_e_salary_63d04b_idx')],
            },
        ),
    ]
