# Generated by Django 5.2.7 on 2026-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('manager_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department_name'],
                'indexes': [models.Index(fields=['department_name'], name='departments_departm_c4f7ca_idx'), models.Index(fields=['location'], name='departments_locatio_bc0e74_idx')],
            },
        ),
    ]
